# Generated by Django 5.0.2 on 2024-03-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceEntity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("choice_text", models.CharField(max_length=200)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polls.questionentity")),
            ],
        ),
    ]
