# Generated by Django 5.0.3 on 2024-03-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_choiceentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="choiceentity",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
